
services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: robot-rl
    volumes:
      - ./robot-rl:/app
      - /tmp/.X11-unix:/tmp/.X11-unix # Mount the X11 socket
      - ~/.maniskill:/root/.maniskill
    env_file:
      - .env # Use the .env file
    environment:
      - DISPLAY=${DISPLAY} # Forward the display
      - XAUTHORITY=${XAUTHORITY} # Use XAUTHORITY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "tensorboard --logdir=/app/robot_rl/outputs --host=0.0.0.0 & poetry run python /app/robot_rl/train_robot.py"
  
  train-dry-run:
    extends:
      service: train
    command: poetry run python robot_rl/train_robot.py dry_run=True

  visualize-train:
    extends:
      service: train
    command: poetry run python robot_rl/train_robot.py visualize_episodes=200 disable_logging=True

  visualize-env:
    extends:
      service: train
    command: poetry run python robot_rl/visualize_env.py
  
  eval:
    extends:
      service: train
    command: poetry run python robot_rl/eval_robot.py model_path=outputs/train/2024-06-03/05-31-50_PickCube-v1_tqc/final_ckpt.pt
  
  maniskill-demo:
    extends:
      service: train
    command: poetry run python -m mani_skill.examples.demo_random_action --render-mode human  --shader rt-fast
